# Generated by Django 6.0.4 on 2026-04-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='UKVI Services', max_length=100)),
                ('site_tagline', models.CharField(default='Official UK Visa & Immigration Fees', max_length=200)),
                ('hero_title', models.CharField(default='UK Visa & Immigration Fee Payment Made Easy', max_length=200)),
                ('hero_subtitle', models.TextField(default='Pay your UK visa application fees and Immigration Health Surcharge (IHS) securely and instantly.')),
                ('stat_1_value', models.CharField(default='50K+', max_length=20)),
                ('stat_1_label', models.CharField(default='Applications', max_length=50)),
                ('stat_2_value', models.CharField(default='100%', max_length=20)),
                ('stat_2_label', models.CharField(default='Secure', max_length=50)),
                ('stat_3_value', models.CharField(default='24/7', max_length=20)),
                ('stat_3_label', models.CharField(default='Support', max_length=50)),
                ('contact_email', models.EmailField(default='support@ukviservices.co.uk', max_length=254)),
                ('contact_phone', models.CharField(default='+44 20 0000 0000', max_length=30)),
                ('footer_text', models.CharField(default='Not affiliated with the UK Home Office.', max_length=300)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.CharField(choices=[('🛂', '🛂 Passport Control'), ('✈️', '✈️ Airplane'), ('🏥', '🏥 Hospital'), ('💳', '💳 Card'), ('📋', '📋 Document')], default='💳', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
    ]
